In [56]:
import numpy as np

## 1. DataTypes & Attributes

In [57]:
# Numpy's main datatype is ndarray
al = np.array([1, 2, 3])
al

array([1, 2, 3])

In [58]:
type(al)

numpy.ndarray

In [59]:
a2 = np.array([[1,2.0,3.3], [4,5,6.5]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [60]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [61]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [62]:
al.shape

(3,)

In [63]:
a2.shape

(2, 3)

In [64]:
a3.shape

(2, 3, 3)

In [65]:
al.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [66]:
al.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [67]:
al.size, a2.size, a3.size

(3, 6, 18)

In [68]:
type(al), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [69]:
#Create a dataFreame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Create arrays

In [70]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [71]:
sample_array.dtype

dtype('int32')

In [72]:
ones = np.ones((2,3))

In [73]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
ones.dtype

dtype('float64')

In [75]:
type(ones)

numpy.ndarray

In [76]:
zeros = np.zeros((2,3))

In [77]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [79]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[0, 5, 3, 0, 5],
       [7, 1, 8, 4, 9],
       [0, 2, 0, 7, 6]])

In [80]:
random_array.size

15

In [81]:
random_array.shape

(3, 5)

In [82]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.55054305, 0.52259111, 0.48755248],
       [0.26303148, 0.52728579, 0.98446573],
       [0.62342345, 0.62955693, 0.9099729 ],
       [0.96251949, 0.5850998 , 0.16489774],
       [0.39159332, 0.94455493, 0.34339118]])

In [83]:
random_array_2.shape

(5, 3)

In [84]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.70507037, 0.4628868 , 0.38679069],
       [0.52843256, 0.82168992, 0.63847702],
       [0.86288872, 0.63662654, 0.99929706],
       [0.51778008, 0.32761664, 0.09877324],
       [0.5667664 , 0.21520794, 0.01179079]])

In [85]:
# # Pseudo-random number
np.random.seed(seed=12)
# random_array_4
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 1, 2],
       [3, 3, 0],
       [6, 1, 4],
       [5, 9, 2],
       [6, 0, 5]])

In [86]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [87]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [88]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 9])

In [89]:
al

array([1, 2, 3])

In [90]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [91]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [92]:
al[0]

1

In [93]:
a2[0]

array([1. , 2. , 3.3])

In [94]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
a2[1]

array([4. , 5. , 6.5])

In [96]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [97]:
a4 = np. random.randint(10, size =(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [98]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [99]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## Manipulating and comparing arrays

Arithmetic

In [100]:
al

array([1, 2, 3])

In [101]:
ones =  np.ones(3)
ones

array([1., 1., 1.])

In [102]:
al + ones

array([2., 3., 4.])

In [103]:
al - ones

array([0., 1., 2.])

In [104]:
al * ones

array([1., 2., 3.])

In [105]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [106]:
al * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [107]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"
# a2 * a3

In [108]:
al / ones

array([1., 2., 3.])

In [109]:
a2 / al

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [110]:
a2 // al

array([[1., 1., 1.],
       [4., 2., 2.]])

In [111]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [112]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [113]:
np.add(al , ones)

array([2., 3., 4.])

In [114]:
al / 2

array([0.5, 1. , 1.5])

In [115]:
al % 2

array([1, 0, 1], dtype=int32)

In [116]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

### Aggregation
#### Aggregation = performing the same operation on a number of things

In [117]:
listy_list = [1,2,3]
type (listy_list)

list

In [118]:
sum(listy_list)

6

In [119]:
sum(al)

6

In [120]:
np.sum(al)

6

### Use Python's methods(sum()) on Python datatypes and use Numpy's methods on Numpy arrays(np.sum())

In [121]:
# Create a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [122]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [123]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

9.4 ms ± 227 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
31.5 μs ± 1.23 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [124]:
np.mean(a2)

3.6333333333333333

In [125]:
np.min(a2)

1.0

In [126]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [127]:
# Variance = measure of the average degree to which each number is different to the mean
np.var(a2)

3.3222222222222224

In [128]:
np.sqrt(np.var(a2))

1.8226964152656422

In [129]:
# Demo of std and var
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [130]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [131]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [132]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)